"""made user_id and guild_id primary keys

Revision ID: 10dfa1d81709
Revises: 3d3c856a5c36
Create Date: 2022-06-04 15:33:39.500492

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "10dfa1d81709"
down_revision = "3d3c856a5c36"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table("members") as batch_op:
        batch_op.create_primary_key("pk_members", ["user_id", "guild_id"])
        batch_op.drop_column("id")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("members", sa.Column("id", sa.BIGINT(), nullable=False))
    # ### end Alembic commands ###
