"""made members.id string type

Revision ID: a7c475a16760
Revises: 3d3c856a5c36
Create Date: 2022-04-27 15:29:00.192735

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "a7c475a16760"
down_revision = "3d3c856a5c36"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
