"""added guild settings model

Revision ID: d9b0c6e2f0b0
Revises: 10dfa1d81709
Create Date: 2022-06-05 14:34:11.515099

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "d9b0c6e2f0b0"
down_revision = "10dfa1d81709"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "guild_settings",
        sa.Column("guild_id", sa.BigInteger(), nullable=False),
        sa.Column("levels_channel", sa.BigInteger(), nullable=True),
        sa.Column("levels_enabled", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("guild_id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("guild_settings")
    # ### end Alembic commands ###
